name: Test

on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - main

# permission can be added at job level or workflow level
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Run linters
        run: |
          python -m pip install --upgrade pip;
          pip install pylint;
          pip install flake8;
          make flake8;
          make pylint;
